<?php

/**
 * @file
 * Contains news_room_admin.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function news_room_admin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the news_room_admin module.
    case 'help.page.news_room_admin':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Admin functionality for a news website.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function news_room_admin_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'create_article':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('News article created: @title', ['@title' => $params['node_title']], $options);
      $message['body'][] = t('Category: @category', ['@category' => $params['category']], $options);
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Implements hook_entity_insert().
 */
function news_room_admin_entity_insert(EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'news')) {
    return;
  }

  $mailManager = \Drupal::service('plugin.manager.mail');

  $module = 'news_room_admin';
  $key = 'create_news';
  $to = "shane@codekarate.com";
  $params['body'] = $entity->get('body')->value;
  $params['node_title'] = $entity->label();
  $params['category'] = $entity->get('field_category')->value;
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = TRUE;

  $result = $mailManager->mail($module, $key, $to, $langcode, $params, TRUE, $send);
  if ($result['result'] !== TRUE) {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }
  else {
    drupal_set_message(t('Your message has been sent.'));
  }
}
